# Generated by Django 5.0.7 on 2024-08-09 17:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(unique=True)),
                ('cat_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField()),
                ('item_desc', models.CharField()),
                ('item_image', models.CharField()),
                ('item_count', models.IntegerField()),
                ('item_active', models.BooleanField()),
                ('item_price', models.IntegerField()),
                ('item_discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('item_date', models.DateField(auto_now=True)),
                ('item_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category')),
            ],
        ),
    ]
