# Generated by Django 5.0.7 on 2024-08-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
