# Generated by Django 5.0.7 on 2024-08-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_category_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
