# Generated by Django 5.0.7 on 2024-08-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_item_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
