# Generated by Django 5.0.7 on 2024-08-11 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_item_item_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_favorite',
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('fav_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_favorite', models.BooleanField(default=False)),
                ('fav_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.item')),
                ('fav_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
