# Generated by Django 5.0.7 on 2024-08-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_item_item_favorite_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='item_favorite',
        ),
    ]
