# Generated by Django 5.0.7 on 2024-08-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
