# Generated by Django 5.0.7 on 2024-08-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_cart_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_count',
            field=models.IntegerField(default=0),
        ),
    ]
